import './styles/globals.css'
import { Inter } from 'next/font/google'
import { NextAuthProvider } from './providers'
import React from 'react'
import { MainNav } from './components/nav.component'



const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
  modal,
  props,
}: {
  children: React.ReactNode,
  modal: React.ReactNode,
  props: React.ReactNode,
 
}) {
 

  
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextAuthProvider>
          {modal}
          {children}
        </NextAuthProvider>
      </body>
    </html>
  )
}
