import "../styles/globals.css";
import { Inter } from "next/font/google";
import { NextAuthProvider } from "./providers";
import React from "react";
import { MainNav } from "@/components/nav.component";
import { Toaster } from "@/components/shared/toaster";
import { Analytics } from '@vercel/analytics/react';

import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Probably",
  description: "Generated by create next app",
  icons: [{rel: "icon", url: "/favicon.ico"}]
};

export default function RootLayout({
  children,
  modal,
}: {
  children: React.ReactNode;
  modal: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="favicon.ico" sizes="any"/>
      </head>
      <body >
        <NextAuthProvider>
          <Toaster />
          {modal}
          {children}
        </NextAuthProvider>
        <Analytics />
      </body>
    </html>
  );
}
